import React from 'react';
import { SafeAreaView } from 'react-native';
import globalStyle from './assets/styles/globalStyle';
import Home from './src/screens/Home/Home';
import Categories from './src/screens/Categories/Categories';
import Results from './src/screens/Results/Results';
import Details from './src/screens/Details/Details';
import OnBoarding from './src/screens/Onboarding/OnBoarding';
import Saved from './src/screens/Saved/Saved';

const App = () => {
    const recipes = [
        {
            idMeal: '52768',
            strMeal: 'Apple Frangipan Tart',
            strDrinkAlternate: null,
            strCategory: 'Dessert',
            strArea: 'British',
            strInstructions:
                'Preheat the oven to 200C/180C Fan/Gas 6.\r\nPut the biscuits in a large re-sealable freezer bag and bash with a rolling pin into fine crumbs. Melt the butter in a small pan, then add the biscuit crumbs and stir until coated with butter. Tip into the tart tin and, using the back of a spoon, press over the base and sides of the tin to give an even layer. Chill in the fridge while you make the filling.\r\nCream together the butter and sugar until light and fluffy. You can do this in a food processor if you have one. Process for 2-3 minutes. Mix in the eggs, then add the ground almonds and almond extract and blend until well combined.\r\nPeel the apples, and cut thin slices of apple. Do this at the last minute to prevent the apple going brown. Arrange the slices over the biscuit base. Spread the frangipane filling evenly on top. Level the surface and sprinkle with the flaked almonds.\r\nBake for 20-25 minutes until golden-brown and set.\r\nRemove from the oven and leave to cool for 15 minutes. Remove the sides of the tin. An easy way to do this is to stand the tin on a can of beans and push down gently on the edges of the tin.\r\nTransfer the tart, with the tin base attached, to a serving plate. Serve warm with cream, crème fraiche or ice cream.',
            strMealThumb:
                'https://www.themealdb.com/images/media/meals/wxywrq1468235067.jpg',
            strTags: 'Tart,Baking,Fruity',
            strYoutube: 'https://www.youtube.com/watch?v=rp8Slv4INLk',
            strIngredient1: 'digestive biscuits',
            strIngredient2: 'butter',
            strIngredient3: 'Bramley apples',
            strIngredient4: 'butter, softened',
            strIngredient5: 'caster sugar',
            strIngredient6: 'free-range eggs, beaten',
            strIngredient7: 'ground almonds',
            strIngredient8: 'almond extract',
            strIngredient9: 'flaked almonds',
            strIngredient10: '',
            strIngredient11: '',
            strIngredient12: '',
            strIngredient13: '',
            strIngredient14: '',
            strIngredient15: '',
            strIngredient16: null,
            strIngredient17: null,
            strIngredient18: null,
            strIngredient19: null,
            strIngredient20: null,
            strMeasure1: '175g/6oz',
            strMeasure2: '75g/3oz',
            strMeasure3: '200g/7oz',
            strMeasure4: '75g/3oz',
            strMeasure5: '75g/3oz',
            strMeasure6: '2',
            strMeasure7: '75g/3oz',
            strMeasure8: '1 tsp',
            strMeasure9: '50g/1¾oz',
            strMeasure10: '',
            strMeasure11: '',
            strMeasure12: '',
            strMeasure13: '',
            strMeasure14: '',
            strMeasure15: '',
            strMeasure16: null,
            strMeasure17: null,
            strMeasure18: null,
            strMeasure19: null,
            strMeasure20: null,
            strSource: null,
            strImageSource: null,
            strCreativeCommonsConfirmed: null,
            dateModified: null,
        },
        {
            idMeal: '52893',
            strMeal: 'Apple & Blackberry Crumble',
            strDrinkAlternate: null,
            strCategory: 'Dessert',
            strArea: 'British',
            strInstructions:
                'Heat oven to 190C/170C fan/gas 5. Tip the flour and sugar into a large bowl. Add the butter, then rub into the flour using your fingertips to make a light breadcrumb texture. Do not overwork it or the crumble will become heavy. Sprinkle the mixture evenly over a baking sheet and bake for 15 mins or until lightly coloured.\r\nMeanwhile, for the compote, peel, core and cut the apples into 2cm dice. Put the butter and sugar in a medium saucepan and melt together over a medium heat. Cook for 3 mins until the mixture turns to a light caramel. Stir in the apples and cook for 3 mins. Add the blackberries and cinnamon, and cook for 3 mins more. Cover, remove from the heat, then leave for 2-3 mins to continue cooking in the warmth of the pan.\r\nTo serve, spoon the warm fruit into an ovenproof gratin dish, top with the crumble mix, then reheat in the oven for 5-10 mins. Serve with vanilla ice cream.',
            strMealThumb:
                'https://www.themealdb.com/images/media/meals/xvsurr1511719182.jpg',
            strTags: 'Pudding',
            strYoutube: 'https://www.youtube.com/watch?v=4vhcOwVBDO4',
            strIngredient1: 'Plain Flour',
            strIngredient2: 'Caster Sugar',
            strIngredient3: 'Butter',
            strIngredient4: 'Braeburn Apples',
            strIngredient5: 'Butter',
            strIngredient6: 'Demerara Sugar',
            strIngredient7: 'Blackberrys',
            strIngredient8: 'Cinnamon',
            strIngredient9: 'Ice Cream',
            strIngredient10: '',
            strIngredient11: '',
            strIngredient12: '',
            strIngredient13: '',
            strIngredient14: '',
            strIngredient15: '',
            strIngredient16: '',
            strIngredient17: '',
            strIngredient18: '',
            strIngredient19: '',
            strIngredient20: '',
            strMeasure1: '120g',
            strMeasure2: '60g',
            strMeasure3: '60g',
            strMeasure4: '300g',
            strMeasure5: '30g',
            strMeasure6: '30g',
            strMeasure7: '120g',
            strMeasure8: '¼ teaspoon',
            strMeasure9: 'to serve',
            strMeasure10: '',
            strMeasure11: '',
            strMeasure12: '',
            strMeasure13: '',
            strMeasure14: '',
            strMeasure15: '',
            strMeasure16: '',
            strMeasure17: '',
            strMeasure18: '',
            strMeasure19: '',
            strMeasure20: '',
            strSource:
                'https://www.bbcgoodfood.com/recipes/778642/apple-and-blackberry-crumble',
            strImageSource: null,
            strCreativeCommonsConfirmed: null,
            dateModified: null,
        },
        {
            idMeal: '53049',
            strMeal: 'Apam balik',
            strDrinkAlternate: null,
            strCategory: 'Dessert',
            strArea: 'Malaysian',
            strInstructions:
                'Mix milk, oil and egg together. Sift flour, baking powder and salt into the mixture. Stir well until all ingredients are combined evenly.\r\n\r\nSpread some batter onto the pan. Spread a thin layer of batter to the side of the pan. Cover the pan for 30-60 seconds until small air bubbles appear.\r\n\r\nAdd butter, cream corn, crushed peanuts and sugar onto the pancake. Fold the pancake into half once the bottom surface is browned.\r\n\r\nCut into wedges and best eaten when it is warm.',
            strMealThumb:
                'https://www.themealdb.com/images/media/meals/adxcbq1619787919.jpg',
            strTags: null,
            strYoutube: 'https://www.youtube.com/watch?v=6R8ffRRJcrg',
            strIngredient1: 'Milk',
            strIngredient2: 'Oil',
            strIngredient3: 'Eggs',
            strIngredient4: 'Flour',
            strIngredient5: 'Baking Powder',
            strIngredient6: 'Salt',
            strIngredient7: 'Unsalted Butter',
            strIngredient8: 'Sugar',
            strIngredient9: 'Peanut Butter',
            strIngredient10: '',
            strIngredient11: '',
            strIngredient12: '',
            strIngredient13: '',
            strIngredient14: '',
            strIngredient15: '',
            strIngredient16: '',
            strIngredient17: '',
            strIngredient18: '',
            strIngredient19: '',
            strIngredient20: '',
            strMeasure1: '200ml',
            strMeasure2: '60ml',
            strMeasure3: '2',
            strMeasure4: '1600g',
            strMeasure5: '3 tsp',
            strMeasure6: '1/2 tsp',
            strMeasure7: '25g',
            strMeasure8: '45g',
            strMeasure9: '3 tbs',
            strMeasure10: ' ',
            strMeasure11: ' ',
            strMeasure12: ' ',
            strMeasure13: ' ',
            strMeasure14: ' ',
            strMeasure15: ' ',
            strMeasure16: ' ',
            strMeasure17: ' ',
            strMeasure18: ' ',
            strMeasure19: ' ',
            strMeasure20: ' ',
            strSource:
                'https://www.nyonyacooking.com/recipes/apam-balik~SJ5WuvsDf9WQ',
            strImageSource: null,
            strCreativeCommonsConfirmed: null,
            dateModified: null,
        },
        {
            idMeal: '53050',
            strMeal: 'Ayam Percik',
            strDrinkAlternate: null,
            strCategory: 'Chicken',
            strArea: 'Malaysian',
            strInstructions:
                "In a blender, add the ingredients for the spice paste and blend until smooth.\r\nOver medium heat, pour the spice paste in a skillet or pan and fry for 10 minutes until fragrant. Add water or oil 1 tablespoon at a time if the paste becomes too dry. Don't burn the paste. Lower the fire slightly if needed.\r\nAdd the cloves, cardamom, tamarind pulp, coconut milk, water, sugar and salt. Turn the heat up and bring the mixture to boil. Turn the heat to medium low and simmer for 10 minutes. Stir occasionally. It will reduce slightly. This is the marinade/sauce, so taste and adjust seasoning if necessary. Don't worry if it's slightly bitter. It will go away when roasting.\r\nWhen the marinade/sauce has cooled, pour everything over the chicken and marinate overnight to two days.\r\nPreheat the oven to 425 F.\r\nRemove the chicken from the marinade. Spoon the marinade onto a greased (or aluminum lined) baking sheet. Lay the chicken on top of the sauce (make sure the chicken covers the sauce and the sauce isn't exposed or it'll burn) and spread the remaining marinade on the chicken. Roast for 35-45 minutes or until internal temp of the thickest part of chicken is at least 175 F.\r\nLet chicken rest for 5 minutes. Brush the chicken with some of the oil. Serve chicken with the sauce over steamed rice (or coconut rice).",
            strMealThumb:
                'https://www.themealdb.com/images/media/meals/020z181619788503.jpg',
            strTags: null,
            strYoutube: 'https://www.youtube.com/watch?v=9ytR28QK6I8',
            strIngredient1: 'Chicken Thighs',
            strIngredient2: 'Challots',
            strIngredient3: 'Ginger',
            strIngredient4: 'Garlic Clove',
            strIngredient5: 'Cayenne Pepper',
            strIngredient6: 'Turmeric',
            strIngredient7: 'Cumin',
            strIngredient8: 'Coriander',
            strIngredient9: 'Fennel',
            strIngredient10: 'Tamarind Paste',
            strIngredient11: 'Coconut Milk',
            strIngredient12: 'Sugar',
            strIngredient13: 'Water',
            strIngredient14: '',
            strIngredient15: '',
            strIngredient16: '',
            strIngredient17: '',
            strIngredient18: '',
            strIngredient19: '',
            strIngredient20: '',
            strMeasure1: '6',
            strMeasure2: '16',
            strMeasure3: '1 1/2 ',
            strMeasure4: '6',
            strMeasure5: '8',
            strMeasure6: '2 tbs',
            strMeasure7: '1 1/2 ',
            strMeasure8: '1 1/2 ',
            strMeasure9: '1 1/2 ',
            strMeasure10: '2 tbs',
            strMeasure11: '1 can ',
            strMeasure12: '1 tsp ',
            strMeasure13: '1 cup ',
            strMeasure14: ' ',
            strMeasure15: ' ',
            strMeasure16: ' ',
            strMeasure17: ' ',
            strMeasure18: ' ',
            strMeasure19: ' ',
            strMeasure20: ' ',
            strSource:
                'http://www.curiousnut.com/roasted-spiced-chicken-ayam-percik/',
            strImageSource: null,
            strCreativeCommonsConfirmed: null,
            dateModified: null,
        },
        {
            idMeal: '52773',
            strMeal: 'Honey Teriyaki Salmon',
            strDrinkAlternate: null,
            strCategory: 'Seafood',
            strArea: 'Japanese',
            strInstructions:
                'Mix all the ingredients in the Honey Teriyaki Glaze together. Whisk to blend well. Combine the salmon and the Glaze together.\r\n\r\nHeat up a skillet on medium-low heat. Add the oil, Pan-fry the salmon on both sides until it’s completely cooked inside and the glaze thickens.\r\n\r\nGarnish with sesame and serve immediately.',
            strMealThumb:
                'https://www.themealdb.com/images/media/meals/xxyupu1468262513.jpg',
            strTags: 'Fish,Breakfast,DateNight',
            strYoutube: 'https://www.youtube.com/watch?v=4MpYuaJsvRw',
            strIngredient1: 'Salmon',
            strIngredient2: 'Olive oil',
            strIngredient3: 'Soy Sauce',
            strIngredient4: 'Sake',
            strIngredient5: 'Sesame Seed',
            strIngredient6: '',
            strIngredient7: '',
            strIngredient8: '',
            strIngredient9: '',
            strIngredient10: '',
            strIngredient11: '',
            strIngredient12: '',
            strIngredient13: '',
            strIngredient14: '',
            strIngredient15: '',
            strIngredient16: null,
            strIngredient17: null,
            strIngredient18: null,
            strIngredient19: null,
            strIngredient20: null,
            strMeasure1: '1 lb',
            strMeasure2: '1 tablespoon',
            strMeasure3: '2 tablespoons',
            strMeasure4: '2 tablespoons',
            strMeasure5: '4 tablespoons',
            strMeasure6: '',
            strMeasure7: '',
            strMeasure8: '',
            strMeasure9: '',
            strMeasure10: '',
            strMeasure11: '',
            strMeasure12: '',
            strMeasure13: '',
            strMeasure14: '',
            strMeasure15: '',
            strMeasure16: null,
            strMeasure17: null,
            strMeasure18: null,
            strMeasure19: null,
            strMeasure20: null,
            strSource: null,
            strImageSource: null,
            strCreativeCommonsConfirmed: null,
            dateModified: null,
        },
        {
            idMeal: '52787',
            strMeal: 'Hot Chocolate Fudge',
            strDrinkAlternate: null,
            strCategory: 'Dessert',
            strArea: 'American',
            strInstructions:
                'Line an 8-inch-square baking pan with wax paper or foil, and coat with non-stick spray.\r\nIn a microwave-safe bowl, combine the dark chocolate chips, heavy cream and half of the sweetened condensed milk. Microwave the dark chocolate mixture in 20-second intervals, stirring in between each interval, until the chocolate is melted.\r\nAdd the vanilla extract to the dark chocolate mixture and stir well until smooth.\r\nTransfer the dark chocolate mixture into the prepared pan and spread into an even layer.\r\nIn a separate bowl, combine the white chocolate chips with the remaining half of the sweetened condensed milk. Microwave the white chocolate mixture in 20-second intervals, stirring in between each interval, until the chocolate is melted.\r\nEvenly spread the white chocolate mixture on top of dark chocolate layer.\r\nTop the chocolate layers with the Mallow Bits or miniature marshmallows, and gently press them down.\r\nRefrigerate for 4 hours, or until set.\r\nRemove the fudge and wax paper from the pan. Carefully peel all of the wax paper from the fudge.\r\nCut the fudge into bite-sized pieces and serve.',
            strMealThumb:
                'https://www.themealdb.com/images/media/meals/xrysxr1483568462.jpg',
            strTags: 'Snack,Chocolate',
            strYoutube: 'https://www.youtube.com/watch?v=oJvbsVSblfk',
            strIngredient1: 'Chocolate Chips',
            strIngredient2: 'Heavy Cream',
            strIngredient3: 'Condensed Milk',
            strIngredient4: 'Vanilla Extract',
            strIngredient5: 'White Chocolate Chips',
            strIngredient6: 'Miniature Marshmallows',
            strIngredient7: '',
            strIngredient8: '',
            strIngredient9: '',
            strIngredient10: '',
            strIngredient11: '',
            strIngredient12: '',
            strIngredient13: '',
            strIngredient14: '',
            strIngredient15: '',
            strIngredient16: '',
            strIngredient17: '',
            strIngredient18: '',
            strIngredient19: '',
            strIngredient20: '',
            strMeasure1: '2 cups',
            strMeasure2: '2 tbs',
            strMeasure3: '1 – 14-ounce can',
            strMeasure4: '1 tsp',
            strMeasure5: '1-⅓ cups',
            strMeasure6: '1-½ cups',
            strMeasure7: '',
            strMeasure8: '',
            strMeasure9: '',
            strMeasure10: '',
            strMeasure11: '',
            strMeasure12: '',
            strMeasure13: '',
            strMeasure14: '',
            strMeasure15: '',
            strMeasure16: '',
            strMeasure17: '',
            strMeasure18: '',
            strMeasure19: '',
            strMeasure20: '',
            strSource: '',
            strImageSource: null,
            strCreativeCommonsConfirmed: null,
            dateModified: null,
        },
        {
            idMeal: '52954',
            strMeal: 'Hot and Sour Soup',
            strDrinkAlternate: null,
            strCategory: 'Pork',
            strArea: 'Chinese',
            strInstructions:
                "STEP 1 - MAKING THE SOUP\r\nIn a wok add chicken broth and wait for it to boil.\r\nNext add salt, sugar, sesame seed oil, white pepper, hot pepper sauce, vinegar and soy sauce and stir for few seconds.\r\nAdd Tofu, mushrooms, black wood ear mushrooms to the wok.\r\nTo thicken the sauce, whisk together 1 Tablespoon of cornstarch and 2 Tablespoon of water in a bowl and slowly add to your soup until it's the right thickness.\r\nNext add 1 egg slightly beaten with a knife or fork and add it to the soup and stir for 8 seconds\r\nServe the soup in a bowl and add the bbq pork and sliced green onions on top.",
            strMealThumb:
                'https://www.themealdb.com/images/media/meals/1529445893.jpg',
            strTags: 'Soup',
            strYoutube: 'https://www.youtube.com/watch?v=KgV9Zq3aSTo',
            strIngredient1: 'Mushrooms',
            strIngredient2: 'Wood Ear Mushrooms',
            strIngredient3: 'Tofu',
            strIngredient4: 'Pork',
            strIngredient5: 'Chicken Stock',
            strIngredient6: 'Salt',
            strIngredient7: 'Sugar',
            strIngredient8: 'Sesame Seed Oil',
            strIngredient9: 'Pepper',
            strIngredient10: 'Hotsauce',
            strIngredient11: 'Vinegar',
            strIngredient12: 'Soy Sauce',
            strIngredient13: 'Cornstarch',
            strIngredient14: 'Water',
            strIngredient15: 'Spring Onions',
            strIngredient16: '',
            strIngredient17: '',
            strIngredient18: '',
            strIngredient19: '',
            strIngredient20: '',
            strMeasure1: '1/3 cup',
            strMeasure2: '1/3 cup',
            strMeasure3: '2/3 Cup',
            strMeasure4: '1/2 cup ',
            strMeasure5: '2-1/2 cups',
            strMeasure6: '1/2 tsp',
            strMeasure7: '1/4 tsp',
            strMeasure8: '1 tsp ',
            strMeasure9: '1/4 tsp',
            strMeasure10: '1/2 tsp',
            strMeasure11: '1-½ cups',
            strMeasure12: '1 tsp ',
            strMeasure13: '1 tbs',
            strMeasure14: '2 tbs',
            strMeasure15: '1/4 cup',
            strMeasure16: '',
            strMeasure17: '',
            strMeasure18: '',
            strMeasure19: '',
            strMeasure20: '',
            strSource:
                'https://sueandgambo.com/pages/chinese-hot-and-sour-soup',
            strImageSource: null,
            strCreativeCommonsConfirmed: null,
            dateModified: null,
        },
        {
            idMeal: '52967',
            strMeal: 'Home-made Mandazi',
            strDrinkAlternate: null,
            strCategory: 'Breakfast',
            strArea: 'Kenyan',
            strInstructions:
                'This is one recipe a lot of people have requested and I have tried to make it as simple as possible and I hope it will work for you. Make sure you use the right flour which is basically one with raising agents. Adjust the amount of sugar to your taste and try using different flavours to have variety whenever you have them.\r\nYou can use Coconut milk instead of regular milk, you can also add desiccated coconut to the dry flour or other spices like powdered cloves or cinnamon.\r\nFor “healthy looking” mandazis do not roll the dough too thin before frying and use the procedure I have indicated above.\r\n\r\n1. Mix the flour,cinnamon and sugar in a suitable bowl.\r\n2. In a separate bowl whisk the egg into the milk\r\n3. Make a well at the centre of the flour and add the milk and egg mixture and slowly mix to form a dough.\r\n4. Knead the dough for 3-4 minutes or until it stops sticking to the sides of the bowl and you have a smooth surface.\r\n5. Cover the dough with a damp cloth  and allow to rest for 15 minutes.\r\n6. Roll the dough on a lightly floured surface into a 1cm thick piece.\r\n7. Using a sharp small knife, cut the dough into the desired size setting aside ready for deep frying.\r\n8. Heat your oil in a suitable pot and gently dip the mandazi pieces to cook until light brown on the first side then turn to cook on the second side.\r\n9. Serve them warm or cold',
            strMealThumb:
                'https://www.themealdb.com/images/media/meals/thazgm1555350962.jpg',
            strTags: 'Baking,Breakfast,Egg,Warm,Snack',
            strYoutube: '',
            strIngredient1: 'Self-raising Flour',
            strIngredient2: 'Sugar',
            strIngredient3: 'Eggs',
            strIngredient4: 'Milk',
            strIngredient5: '',
            strIngredient6: '',
            strIngredient7: '',
            strIngredient8: '',
            strIngredient9: '',
            strIngredient10: '',
            strIngredient11: '',
            strIngredient12: '',
            strIngredient13: '',
            strIngredient14: '',
            strIngredient15: '',
            strIngredient16: '',
            strIngredient17: '',
            strIngredient18: '',
            strIngredient19: '',
            strIngredient20: '',
            strMeasure1: '750g',
            strMeasure2: '6 tablespoons',
            strMeasure3: '2',
            strMeasure4: '1 cup ',
            strMeasure5: ' ',
            strMeasure6: ' ',
            strMeasure7: ' ',
            strMeasure8: ' ',
            strMeasure9: ' ',
            strMeasure10: ' ',
            strMeasure11: ' ',
            strMeasure12: ' ',
            strMeasure13: ' ',
            strMeasure14: ' ',
            strMeasure15: ' ',
            strMeasure16: ' ',
            strMeasure17: ' ',
            strMeasure18: ' ',
            strMeasure19: ' ',
            strMeasure20: ' ',
            strSource:
                'http://chef-raphael.com/home-made-mandazi-recipe/#more-106',
            strImageSource: null,
            strCreativeCommonsConfirmed: null,
            dateModified: null,
        },
        {
            idMeal: '52993',
            strMeal: 'Honey Balsamic Chicken with Crispy Broccoli & Potatoes',
            strDrinkAlternate: null,
            strCategory: 'Chicken',
            strArea: 'American',
            strInstructions:
                "2 Servings\r\n\r\n1. Preheat oven to 425 degrees. Wash and dry all produce. Cut potatoes into 1/2-inch-thick wedges. Toss on one side of a baking sheet with a drizzle of oil, salt, and pepper. (For 4 servings, spread potatoes out across entire sheet.) Roast on top rack for 5 minutes (we'll add the broccoli then). \r\n\r\n2. Meanwhile, cut broccoli florets into bite-size pieces, if necessary. Peel and finely chop garlic. In a small microwave-safe bowl, combine 1 TBSP olive oil (2 TBSP for 4 servings) and half the garlic. Microwave until garlic sizzles, 30 seconds. \r\n\r\n3. Once potatoes have roasted 5 minutes, remove sheet from oven and add broccoli to empty side; carefully toss with garlic oil, salt, and pepper. (For 4 servings, add broccoli to a second sheet.) Continue roasting until potatoes and broccoli are browned and crispy, 15-20 minutes more. \r\n\r\n4. While veggies roast, pat chicken dry with paper towels; season all over with salt and pepper. Heat a drizzle of oil in a large pan over medium-high heat. Add chicken and cook until browned and cooked through, 5-6 minutes per side. (If chicken browns too quickly, reduce heat to medium.) Turn off heat; set chicken aside to rest. Wash out pan. \r\n\r\n5. Heat pan used for chicken over medium-high heat. Add a drizzle of oil and remaining garlic; cook until fragrant, 30 seconds. Stir in vinegar, honey, stock concentrate, and 1/4 cup water (1/3 cup for 4 servings). Simmer until thick and glossy, 2-3 minutes. Remove from heat and stir in 1 TBSP butter (2 TBSP for 4). Season with salt and pepper. \r\n\r\n6. Return chicken to pan and turn to coat in glaze. Divide chicken, broccoli, and potatoes between plates. Spoon any remaining glaze over chicken and serve. ",
            strMealThumb:
                'https://www.themealdb.com/images/media/meals/kvbotn1581012881.jpg',
            strTags: null,
            strYoutube: '',
            strIngredient1: 'Potatoes',
            strIngredient2: 'Broccoli',
            strIngredient3: 'Garlic',
            strIngredient4: 'Chicken Breast',
            strIngredient5: 'Balsamic Vinegar',
            strIngredient6: 'Honey',
            strIngredient7: 'Chicken Stock',
            strIngredient8: 'Butter',
            strIngredient9: 'Vegetable Oil',
            strIngredient10: 'Olive Oil',
            strIngredient11: '',
            strIngredient12: '',
            strIngredient13: '',
            strIngredient14: '',
            strIngredient15: '',
            strIngredient16: '',
            strIngredient17: '',
            strIngredient18: '',
            strIngredient19: '',
            strIngredient20: '',
            strMeasure1: '5',
            strMeasure2: '1',
            strMeasure3: '2 cloves',
            strMeasure4: '2',
            strMeasure5: ' ',
            strMeasure6: ' ',
            strMeasure7: ' ',
            strMeasure8: '1 tbsp',
            strMeasure9: '1 tbsp',
            strMeasure10: '1 tbsp',
            strMeasure11: ' ',
            strMeasure12: ' ',
            strMeasure13: ' ',
            strMeasure14: ' ',
            strMeasure15: ' ',
            strMeasure16: ' ',
            strMeasure17: ' ',
            strMeasure18: ' ',
            strMeasure19: ' ',
            strMeasure20: ' ',
            strSource: '',
            strImageSource: null,
            strCreativeCommonsConfirmed: null,
            dateModified: null,
        },
        {
            idMeal: '53007',
            strMeal: 'Honey Yogurt Cheesecake',
            strDrinkAlternate: null,
            strCategory: 'Dessert',
            strArea: 'Greek',
            strInstructions:
                'Heat oven to 160C/140C fan/gas 3. Crush the biscuits and most of the almonds inside a plastic food bag using a rolling pin. Mix with the butter, then press into the bottom of a deep, oval, 23cm dish (or something similar in size – a roasting tin, baking dish or cake tin will work). Bake for 10 mins until crisp.\r\n\r\nStir or mash together the yogurt and mascarpone, then whisk in the eggs, one at a time. Stir in the lemon and orange zests, then stir in most of the honey, reserving about 3 tbsp. Spread over the biscuit base, cover loosely with foil and cook for 1 hr. Remove the foil and cook for 15 mins more until lightly golden and the top is firm with just the slightest wobble in the middle. Leave to cool. Can be kept in the fridge for up to 2 days.\r\n\r\nTo serve, scatter with almonds, drizzle over the remaining honey, and hand around fresh fruit to go with it.',
            strMealThumb:
                'https://www.themealdb.com/images/media/meals/y2irzl1585563479.jpg',
            strTags: null,
            strYoutube: 'https://www.youtube.com/watch?v=JE8crtueXs8',
            strIngredient1: 'Digestive Biscuits',
            strIngredient2: 'Almonds',
            strIngredient3: 'Butter',
            strIngredient4: 'Greek Yogurt',
            strIngredient5: 'Mascarpone',
            strIngredient6: 'Eggs',
            strIngredient7: 'Lemon',
            strIngredient8: 'Orange',
            strIngredient9: 'Honey',
            strIngredient10: 'Fruit Mix',
            strIngredient11: '',
            strIngredient12: '',
            strIngredient13: '',
            strIngredient14: '',
            strIngredient15: '',
            strIngredient16: '',
            strIngredient17: '',
            strIngredient18: '',
            strIngredient19: '',
            strIngredient20: '',
            strMeasure1: '100g ',
            strMeasure2: '85g',
            strMeasure3: '85g',
            strMeasure4: '250ml',
            strMeasure5: '750g',
            strMeasure6: '2',
            strMeasure7: 'Zest of 1',
            strMeasure8: 'Zest of 1',
            strMeasure9: '250ml',
            strMeasure10: 'To serve',
            strMeasure11: ' ',
            strMeasure12: ' ',
            strMeasure13: ' ',
            strMeasure14: ' ',
            strMeasure15: ' ',
            strMeasure16: ' ',
            strMeasure17: ' ',
            strMeasure18: ' ',
            strMeasure19: ' ',
            strMeasure20: ' ',
            strSource:
                'https://www.bbcgoodfood.com/recipes/honey-yogurt-cheesecake',
            strImageSource: null,
            strCreativeCommonsConfirmed: null,
            dateModified: null,
        },
        {
            idMeal: '53035',
            strMeal: 'Ham hock colcannon',
            strDrinkAlternate: null,
            strCategory: 'Pork',
            strArea: 'Irish',
            strInstructions:
                'STEP 1\r\nPeel and cut the potatoes into even, medium-sized chunks. Put in a large pan filled with cold salted water, bring to the boil and cook for 10-15 mins until a knife can be inserted into the potatoes easily.\r\n\r\nSTEP 2\r\nMeanwhile, melt the butter in a large sauté pan over a medium heat. Add the garlic, cabbage, spring onions and some seasoning. Stir occasionally until the cabbage is wilted but still retains a little bite, then set aside.\r\n\r\nSTEP 3\r\nDrain the potatoes, leave to steam-dry for a couple of mins, then mash with the cream, mustard and seasoning in the same saucepan. Stir in the cabbage and ham hock. Keep warm over a low heat.\r\n\r\nSTEP 4\r\nReheat the pan you used to cook the cabbage (no need to wash first), add a splash of oil, crack in the eggs and fry to your liking. To serve, divide the colcannon between bowls and top each with a fried egg.',
            strMealThumb:
                'https://www.themealdb.com/images/media/meals/n41ny81608588066.jpg',
            strTags: null,
            strYoutube: 'https://www.youtube.com/watch?v=aQJAU2iJ730',
            strIngredient1: 'Floury Potatoes',
            strIngredient2: 'Butter',
            strIngredient3: 'Garlic Clove',
            strIngredient4: 'Cabbage',
            strIngredient5: 'Spring Onions',
            strIngredient6: 'Double Cream',
            strIngredient7: 'Mustard',
            strIngredient8: 'Ham',
            strIngredient9: 'Eggs',
            strIngredient10: '',
            strIngredient11: '',
            strIngredient12: '',
            strIngredient13: '',
            strIngredient14: '',
            strIngredient15: '',
            strIngredient16: '',
            strIngredient17: '',
            strIngredient18: '',
            strIngredient19: '',
            strIngredient20: '',
            strMeasure1: '800g',
            strMeasure2: '50g',
            strMeasure3: '3 chopped',
            strMeasure4: '1 chopped',
            strMeasure5: '8',
            strMeasure6: '100ml',
            strMeasure7: '2 tbs',
            strMeasure8: '180g',
            strMeasure9: '4',
            strMeasure10: ' ',
            strMeasure11: ' ',
            strMeasure12: ' ',
            strMeasure13: ' ',
            strMeasure14: ' ',
            strMeasure15: ' ',
            strMeasure16: ' ',
            strMeasure17: ' ',
            strMeasure18: ' ',
            strMeasure19: ' ',
            strMeasure20: ' ',
            strSource: 'https://www.bbcgoodfood.com/recipes/ham-hock-colcannon',
            strImageSource: null,
            strCreativeCommonsConfirmed: null,
            dateModified: null,
        },
    ];
    return (
        // <OnBoarding />
        // <Details onPress={() => {}} recipeItem={recipes[3]} />
        <SafeAreaView style={[globalStyle.flex, globalStyle.marginHorizontal]}>
            {/* <Home /> */}
            {/* <Categories /> */}
            {/* <Results onPress={() => {}} recipes={recipes} /> */}
            <Saved recipes={recipes} />
        </SafeAreaView>
    );
};

export default App;
